name: "Batch close stale bug and question issues"
permissions:
  contents: read
  issues: write
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Close issues after 3 months of inactivity
        days-before-issue-stale: 90
        days-before-issue-close: 0
        only-issue-labels: "bug,question"
        exempt-issue-labels: "do-not-autoclose,Meta request"
        close-issue-message: "To have a more manageable issue backlog, we're closing older bug reports and questions that weren't addressed within three months. If this issue is still relevant, please [open a new issue](https://github.com/aayush2622/Dartotsu/issues/new/choose)."
        close-issue-reason: not_planned
        ascending: true
        operations-per-run: 250
